Feature/aleste new1
nkosi-tauro/dfrs_domain pull request #44
Opened 2023-07-02 10:00 UTC by alesteka

Take a look

2023-07-02 11:00 UTC, nkosi-tauro requested changes
Make sure to register your model so that it appears in the Admin Panel. 
I have added some comments

2023-07-03 08:44 UTC, alesteka commented on user_service/views.py
> +    return render(request, 'employeeview/edit_flaw.html', context)
done, ran pylint and moved to appropriate folder

2023-07-03 08:45 UTC, alesteka commented on user_service/models.py
> +    def __str__(self):
done

2023-07-03 08:45 UTC, alesteka commented on user_service/models.py
moved

2023-07-03 08:45 UTC, alesteka commented on user_service/views.py
> +        form = AddFlawForm(request.POST)
done

2023-07-03 08:46 UTC, alesteka commented on user_service/models.py
> +    description = models.CharField(max_length=200, blank=True)
changed - done

2023-07-03 10:48 UTC, merged